project:
  type: website
  output-dir: docs
  preview:
    port: 5500

execute:
  freeze: auto

website:
  title: "SWINNO"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: team.qmd
        text: Team
      - href: dashboard.qmd
        text: "Dashboard"
      - href: publications.qmd
        text: Publications
  page-footer:
    background: "#161324"
    left: |
      Copyright &copy; 2024 [SWINNO Project]()

    right: |
      [Terms and Conditions](/tscs.qmd)
  repo-url: https://github.com/swinnoproject/website
  repo-actions: [issue, edit]

format:
  html:
    theme: [lux, bw.scss, archivo.scss]
    css: styles.css
    toc: true
    grid:
      sidebar-width: 0px
      body-width: 750px
      margin-width: 250px
